# Generated by Django 3.2.5 on 2021-08-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_favorite'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'favorite_recipe'), name='user-favorite_recipe'),
        ),
    ]
