# Generated by Django 3.2.5 on 2021-07-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredients',
            name='recipe-ingredients',
        ),
    ]
