# Generated by Django 3.2.5 on 2021-07-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210726_1939'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='recipe-ingredient'),
        ),
    ]
